### ISSUE TITLE
Removal of Plex-Remote-Transcoder

### ISSUE THREAD

**Issue by 1tsmejp** [wnielson/Plex-Remote-Transcoder#23]
Since I installed this its worked pretty awesome however upon install my Plex server lost its ability to offline sync and I also cannot Stream to IOS devices. I was wondering how could i remove this without causing damage to my Plex install. I have already shutdown my Plex Slave host. Are there any particular directories or config files i should remove? I want to restore service to my offline sync and Streaming please let me know if you get an available moment. 

Thanks
Joe

**Comment by liviynz** [comment]
I've been out of the loop for a while so I need to review the background info but this is a known issue with a known fix. Basically the sync uses a custom area for the encoding and the quick fix is to make the /var/lib/plexmediaserver nfs export read/write (or rw) instead of read only (or ro) as stated in the installation guide and that will fix that issue. There has been discussions about how to try and fix this without opening up that whole file structure as read/write and I need to find out where that got to but that will fix your issue as I had it myself. 

In /etc/exports change the ro to rw for the file system 
/var/lib/plexmediaserver

Re-export
`sudo exportfs -r`

And on the slave(s) either unmount and mount that share or to be sure it's all clean just restart the client system and on next boot it should be able to process those other types of jobs.

As for removing if you are determined to do so then you can either just remove the .prt.conf file in the plex user home directory and it will only use the master which has access already and then you can look at fixing it another way or you can either remove this file -
`rm "/usr/lib/plexmediaserver/Resources/Plex New Transcoder"`
Then move the old one back -
`mv /usr/lib/plexmediaserver/Resources/plex_transcoder /usr/lib/plexmediaserver/Resources/Plex New Transcoder`
Or reinstall the plex -
`sudo dpkg-reconfigure plexmediaserver && sudo apt-get -f install`

But as I mentioned changing the export to read/write will fix it.

Cheers,
Liviy

**Comment by liviynz** [comment]
While it's never a good thing to have people want to uninstall your hard work we should probably add a delete and/or a disable option before PRT gets labeled malware due to the lack of it ;)

**Comment by wnielson** [comment]
Yeah, agreed.

**Comment by lpreams** [comment]
Generally installation tutorials will include a section at the end about complete and efficient uninstallation. Since PRT already has a nice Ubuntu tutorial, having a section at the end of that about how to return to a normally-functioning PMS and fully remove everything installed by PRT seems ideal to me.

**Comment by wnielson** [comment]
I added a section to the tutorial about uninstalling.
