### ISSUE TITLE
New Version on Plex breaks remote transcode

### ISSUE THREAD

**Issue by speedminion87** [wnielson/Plex-Remote-Transcoder#27]
Ubuntu 64 Plex update problem...Please can you help?
Hello and may i thank you for this fantastic extension to plex  Have been using it flawlessly for many months now. BUT...
After updating to latest version 0.9.17.2.2159, after many previous upgrades that worked well, running prt install throws up an error that it cant rename plex transcoder.
Some investigation shows that the new install doesn't have "Plex New Transcoder" only "Plex Transcoder" in the /usr/lib/plexmediaserver/Resources directory thus the prt install command fails.
Now the only thing I could think of was to edit prt.py and Change the line looking for "Plex New Transcoder" to "Plex Transcoder" run the 
python steup.py install  and then,
sudo install -o plex -g plex ~/.prt.conf ~plex/, then 
re run prt install.
Now this does rename the Transcoder as before, but then that's all that happens. setup a single host using the add_host command and try to play something that I know needs transcoding on my iPhone, and it just skips it and tries to play the next thing and never actually plays anything.

Watching logs it doesn't even seem to activate the transcoder but i'm not an expert in this script stuff

I'm out of ideas now, so have gone back to version 0.9.16.6 where this remote transcoder still works perfectly.

I'm such a fan of the work you have done here and its been a life saver for me allowing friends and family to all stream without killing the main PMS. 

Please could someone figure out whats going on with the latest version of plex and provide some information or step-by-step to getting this to work on the latest version.

Many Thanks to anyone who can help. Look forward to some genius having the answer :-)

**Comment by Drewster727** [comment]
+1

**Comment by Drewster727** [comment]
@wnielson any ideas?

**Comment by wnielson** [comment]
I haven't had any free time to investigate this yet.  As [liviy pointed out](http://forums.plex.tv/discussion/comment/1196853/#Comment_1196853) the fix for now to is to stay with (or roll back) to 0.9.16.

**Comment by tyronemills** [comment]
Just upgraded my PMS to the newest version and then found this today... :( Can't wait to be able to run this! Might try rolling back tonight rather than waiting.

**Comment by jaretclifton** [comment]
I, unfortunately pulled the trigger stupidly on the 1.0 release without checking here or the plex forum first. It appears transcoding works without PRT in the mix so at least I'm not dead in the water. We all appreciate the hard work you put in!

**Comment by FrostEnergy** [comment]
I had this issue when attempting the install, Solved it by editing the following in the prt.py file

Old: #ORIGINAL_TRANSCODER_NAME = "Plex New Transcoder"
New: ORIGINAL_TRANSCODER_NAME = "Plex Transcoder"

After this run the python setup.py install command again, and continue from there.

My issue now is that the remote transcoder has never worked for me :/
Running server version: 1.0.0.2261

**Comment by liviynz** [comment]
Unfortunately that doesn't fix the issue...I found adjusting that line just meant that some things transcoded and some didn't, appeared very random. I wouldn't recommend doing that.

**Comment by wnielson** [comment]
Have you tried the new branch?

**Comment by liviynz** [comment]
Me? Not yet, I've had fun with partially destroying my os and my backup of my OS in one foul swoop so spent the last 10 days pulling what I could from the wreckage n rebuilding. Massive pain, I'll have a look shortly

**Comment by liviynz** [comment]
Reminds me, I need to re setup my coding suite with all the repos, etc. never try to do a restore from backup when you're tired...

**Comment by speedminion87** [comment]
Hi All. Anyone had any success using the latest version of plex and remote transcode. 
Hoping the developer has some time spare very soon as I'm sure this would take him less than an hour as he knows his work best.
If anyone else has a working solution please share here

Many Thanks in advance

**Comment by Drewster727** [comment]
@speedminion87 This is being worked on. @wnielson created a "PMS-v1" branch. Not sure on the status of it, haven't tried it yet.

**Comment by liviynz** [comment]
I'm currently testing it...well, I will be shortly when my system finishes the last few videos it needs to image index so I can do the upgrade.

**Comment by speedminion87** [comment]
Have just tried and it works locally (if you use local address in add_host) but does not work on remote host, PMS launches the job and then it dies, yet was working before upgrade so not a nfs share problem. have updated prt on both machines.
Any ideas?

**Comment by speedminion87** [comment]
Incase it helps, have had to revert once again back to 0.9.16 version, using prt 2.2 release and all is well again. The only thing i noticed watching top on the remote host is when the PMS tried to start transcode all I saw was prt then prt_local then gone that was it nothing more happened. Tried reboots. Checked NFS shares, still nothing on remote host would not transcode but would do it locally by using loopback address on PMS server... :-(

Again hope this helps please let me know if you need more description  Thanks one and all

**Comment by FrostEnergy** [comment]
I finally got mine working, The author made some changes a few days ago.  Last night I re-downloaded and reinstalled everything on the slave and master, making sure that Plex Transcoder in Resources was re-written by manually reverting it back to stock first.  I am running PMS version 1.0.0.2261 (plex pass update channel).

EDIT: To note, both servers are running Ubuntu 14.04 (virtualized in VMware ESXi).

**Comment by liviynz** [comment]
Well my testing failed, anything via PRT fails with a library error so I'm just hunting that down currently.

**Comment by liviynz** [comment]
Fixed...it seems there was a weird extra directory  /var/lib/plexmediaserver/Library/Application Support/Plex/ and for some weird reason the codecs were going down that path. So I removed plexmediaserver from the system, removed that directory path, removed the plex_transcoder and reinstalled plexmediaserver and did a sudo PRT install. The it all came together again! It's like it got confused buy the path with the spaces somehow!

**Comment by wnielson** [comment]
@liviynz Interesting.  Not sure what you mean by "codecs were going down that path", but glad you got it working.  In my testing, I started with a fresh OS and installed `PMS` 1.0.  On a fresh install things just work.  Perhaps we should put together an upgrade guide for people going from 0.9.x -> 1.0.

**Comment by liviynz** [comment]
/usr/lib/plexmediaserver/Resources/plex_transcoder: error while loading shared libraries: libdcadec.so: cannot open shared object file: No such file or directory

PRT was getting this variable from PMS : FFMPEG_EXTERNAL_LIBS=/var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/Codecs/2c361e4-1071-linux-ubuntu-x86_64/

But all libraries in wrong location due to using "Plex" and not "Plex Media Server"

/var/lib/plexmediaserver/Library/Application Support/Plex/Codecs/2c361e4-1071-linux-ubuntu-x86_64
-rw-r--r-- 1 plex plex  297488 Jun 11 08:14 libaac_encoder.so
-rw-r--r-- 1 plex plex  238872 Jun 11 19:34 libac3_decoder.so
-rw-r--r-- 1 plex plex  465208 Jun 11 08:14 libdca_decoder.so
-rw-r--r-- 1 plex plex 1309976 Jun 11 06:24 libh264_decoder.so
-rw-r--r-- 1 plex plex 1013528 Jun 11 20:20 libhevc_decoder.so
-rw-r--r-- 1 plex plex 1208728 Jun 11 10:26 liblibx264_encoder.so
-rw-r--r-- 1 plex plex  418840 Jun 11 09:56 libmpeg2video_decoder.so
-rw-r--r-- 1 plex plex  618008 Jun 11 06:28 libmpeg4_decoder.so
-rw-r--r-- 1 plex plex  565032 Jun 11 09:46 libmsmpeg4v3_decoder.so
-rw-r--r-- 1 plex plex  234328 Jun 12 00:11 libwmapro_decoder.so
-rw-r--r-- 1 plex plex  242648 Jun 11 10:26 libwmav2_decoder.so
-rw-r--r-- 1 plex plex  610088 Jun 11 09:31 libwmv2_decoder.so
-rw-r--r-- 1 plex plex  844616 Jun 11 06:56 libwmv3_decoder.so

Not all libraries in the correct location

/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Codecs/2c361e4-1071-linux-ubuntu-x86_64

-rw-r--r-- 1 plex plex  297488 Jul  9 03:54 libaac_encoder.so
-rw-r--r-- 1 plex plex  238872 Jul  9 03:54 libac3_decoder.so
-rw-r--r-- 1 plex plex 1309976 Jul  9 03:41 libh264_decoder.so
-rw-r--r-- 1 plex plex 1013528 Jul  9 04:18 libhevc_decoder.so
-rw-r--r-- 1 plex plex  618008 Jul  9 03:44 libmpeg4_decoder.so
-rw-r--r-- 1 plex plex  844616 Jul  9 04:01 libwmv3_decoder.so

I suspect from the earlier release and it had a pathing issue.

**Comment by Drewster727** [comment]
@wnielson an upgrade guide would be awesome...

**Comment by Drewster727** [comment]
Did you guys just backup your PMS Preferences.xml file, re-install, then replace that file?

**Comment by liviynz** [comment]
got a pull request in that fixes the issues I've been seeing since the upgrade : [https://github.com/wnielson/Plex-Remote-Transcoder/pull/34](url)
