### ISSUE TITLE
Unable to start new streams

### ISSUE THREAD

**Issue by Kazz3r24** [wnielson/Plex-Remote-Transcoder#67]
Hey! Firstly, amazing! I've been looking for a way to set up a load-balancing/failover cluster for Plex for a long time and this just about does the trick! (Once I figure out how to set up the load balancing).
Only issue I'm currently having that I'm aware of is, when I have PRT running, I don't quite see it in htop on my Ubuntu VM, but the CPU was definitely being used - I'm hoping for transcoding. While I had it going any streams already in progress continued on, but the issue I ran into was no new streams were able to be started. The media was present and accessible. Everything as far as I could tell was set up correctly, and I had access to the shares.
Is there anything in the logs I can provide in order to help figure this out?

Currently running latest PMS on Ubuntu 16.04 and testing it with a vanilla Ubuntu 16.04 VM.

Thanks again!

**Comment by Kazz3r24** [comment]
Just an update.
I managed to roll back my Plex installation to 1.7.5 paired with prt latest and have gotten everything working.
Looking forward to when this works with the most recent PMS versions!

**Comment by liviynz** [comment]
Hi, PRT is functional with the latest version of PMS...I’m running current across 3 x Ubuntu 16.04 Systems. The fact that you rolled back and could use it again suggests it’s not your basic setup but most likely one of the later versions of PMS has a setting that isn’t being liked. My first guess would be the hardware encoding option for graphic card support. That one isn’t going to work unless all the systems have identical s graphics cards and even then it’s only a maybe due to the way PMS have put their app together so that needs to be unticked until they use one of the more flexible industry standards for dealing with the gpu offloading rather than the ridged one they went with. The second most common hang up with the more recently PMS versions is around the EAE software for HD audio but that doesn’t affect every transcode and there are workarounds/fixes for that. My money is on the gpu option being ticked in the later PMS versions which support it, unticking it should allow normal functioning

**Comment by Kazz3r24** [comment]
Hey Liviy,

Thank you for getting back to me. I do have HW accelerated transcoding on - so that is likely the issue you're right, I'll test that and respond back with my findings. I never thought of that, wish I had! Thinking of it now it makes complete sense.
For the issue with EAE, I'm about to start looking into the workarounds/fixes you mentioned - but should I not be able to find anything through searching myself, are you able to point me in the right direction?

Thank you again for your response!

**Comment by Kazz3r24** [comment]
I think I may have found it, but would like to confirm. Is a fix for the EAE removing the Codecs directory? I have not tried that since I got working. Basically as soon as I saw the transcodes showing up in htop I ran away so I didn't touch anything else while it was working.

**Comment by Kazz3r24** [comment]
I did manage to get prt working on the latest PMS 1.11.3 according to prt check_config. You were right, I just needed to disable hardware accelerated transcoding. I'm pretty sure EAE is still going to be a problem. I haven't removed anything from the Codecs directory yet because I'm not sure yet if that's the correct fix.

**Comment by Kazz3r24** [comment]
Just wanted to mention that I forgot I had this issue still opened. I did eventually get it working using 1.11.x and intended to set the master as a slave as well so it did some transcoding instead of relying solely on the slave server, I just haven't had time to set that up yet. Closing this issue for now, worked great while I had it going!
